### ISSUE TITLE
Allow calls from jenkins pipeline plugin

### ISSUE THREAD

**Issue by dcoraboeuf** [jenkinsci/ontrack-plugin#19]
Integrate Ontrack within the Pipeline plugin.

See nemerosa/ontrack#407

**Comment by dcoraboeuf** [comment]
@flesire 

I will make an `ontrack` global variable available in the DSL, which will allow to code Ontrack calls using directly the DSL. For example:

``` groovy
node (...) {
    ...
    // Creates a build entry
    ontrack.branch('project', 'branch').build(env.BUILD_NUMBER, "Description")
}
```

See https://github.com/jenkinsci/docker-workflow-plugin/blob/master/src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java for an example of global variable definition.

**Comment by dcoraboeuf** [comment]
It's on branch `feature/19-pipeline` but I have difficulties making it work due to difficulties with CPS constraints. I'm working on it when time allows and it should be available in the next weeks.

**Comment by dcoraboeuf** [comment]
As of today, I have to use code like:

```groovy
@NonCPS
def mycall(ontrack) {
    ontrack.branch('test', 'master').build(env.BUILD_NUMBER as String, 'For test', true) {
        validate 'VS1'
    }
}
ontrack {
    mycall(delegate)
}
0
```

Pretty ugly. But I can't get my head around the CPS transformations.

**Comment by dcoraboeuf** [comment]
First step created: `ontrackBuild`... I finally gave up with the CPS transformation, and I'm using regular steps like, for example:

```groovy
...
ontrackBuild(project: 'proj', branch: 'master', build: env.BUILD_NUMBER)
...
```

Now, trying to make some integration tests and creation other steps, including calling the Ontrack DSL (as a string)

**Comment by SansGuidon** [comment]
(initially posted into nemerosa/ontrack#574) 

Hi !

While migrating from classic Jenkins jobs definition to Jenkins declarative pipeline definition, I'm looking for examples of usage of ontrack in and ontrack DSL in context of declarative pipelines.

I'm trying to create jobs parameters whose values are automatically populated by ontrack using ontrack DSL. It was possible to do so before declarative pipeline, using ontrack dsl parameter in the UI, but I didn't find an example of doing the same thing in declarative pipeline.

```groovy
pipeline {
    agent any
    parameters {
        ... // how to create dynamic ontrack parameter here ?
    }
    stages {
        stage('Example') {
            steps {
                ...
            }
        }
    }
}
```

Is it possible ? Could you provide an example if you have any ? A solution to my particular issue or even better, a complete example of declarative pipeline making use of the full potential of ontrack could be a good helper to convice more people to use ontrack, especially since declarative pipeline is the future of jenkins jobs definition.

Thanks a lot :) 

PS : I found this, didn't tested yet, need to be investigated on my side, will provide feedback if I can came up with a solution
https://stackoverflow.com/questions/44570163/jenkins-dynamic-declarative-pipeline-parameters#44626376

**Comment by SansGuidon** [comment]
Current progress is : it works in declarative syntax using the following code, but I hate the result so will keep working on it. 

```
properties([
    parameters([
        [
            $class: 'OntrackChoiceParameterDefinition', 
            description: '', 
            dsl: "ontrack.branch('APS', 'release').standardFilter(count: 5)",
            name: 'RELEASE_NUMBER', 
            valueProperty: 'name',
            sandbox: false
        ]
    ])
])
pipeline {
    agent any
   /* parameters {
        ... // how to create dynamic ontrack parameter here ?
    }*/
    stages {
        stage('Example') {
            steps {
	         echo 'deployment of config for ' + params.RELEASE_NUMBER
            }
        }
    }
}
```

Thanks to that I have a parametrizable build where values are filled by ontrack (see picture : https://i.imgur.com/x7Z8XWm.png )

Next challenge is to make it work with a more user friendly syntax

Tested using Jenkins 2.73.2 + ontrack plugin 2.31.1 with ontrack 2.30.4

What I would like to achieve is to define the parameters as below : 

```
pipeline {
    agent any
    parameters {
        ontrackChoiceParam(name: 'RELEASE_NUMBER', description: '...', dsl: '...', valueProperty: '...')
    }
    stages {
        stage('Example') {
            steps {
	         echo 'deployment of config for ' + params.RELEASE_NUMBER
            }
        }
    }
}
``` 

But in order to have per-plugin parameters recognised by Jenkins, I think it's needed to define a specific Symbol in your classes that extend ParameterDefinition https://github.com/jenkinsci/ontrack-plugin/search?utf8=%E2%9C%93&q=ParameterDescriptor+&type= 

Example here with the credentials plugin where a Symbol annotation is defined 
https://github.com/jenkinsci/credentials-plugin/blob/master/src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java#L115

More info about this problem and solution for credentials plugin, if it's helpful : 
https://issues.jenkins-ci.org/browse/JENKINS-44588
https://github.com/jenkinsci/credentials-plugin/pull/86/files

Cheers
Morgan

**Comment by dcoraboeuf** [comment]
For my information, do you work with the latest build from the `feature/19-pipeline-dsl` branch, or do you use a released version of the plugin?

**Comment by SansGuidon** [comment]
I use the released version of plugin, with versions mentioned in the previous post 

> Tested using Jenkins 2.73.2 + ontrack plugin 2.31.1 with ontrack 2.30.4

**Comment by dcoraboeuf** [comment]
Ah ok :) Sorry. You might want to test by building the `feature/19-pipeline-dsl` locally and publishing the HPI in your Jenkins instance (management of dependencies can be tricky though...)

**Comment by SansGuidon** [comment]
If you already have a HPI of this version available (as I see you are using travis) I can have a look.
Otherwise I'll try to build it and test it on my side :) (cannot promise when It will be done) and keep you informed, it not urgent for you. I will also test with the Symbol annotation added

**Comment by dcoraboeuf** [comment]
It's on my todo list, but I'm currently overflown with other issues :( Not Ontrack related...

**Comment by dcoraboeuf** [comment]
Available in 2.32.0

**Comment by SansGuidon** [comment]
@dcoraboeuf is it possible to implement the @Symbol as suggested in https://github.com/jenkinsci/ontrack-plugin/issues/19#issuecomment-343158592 ? I think it's needed to use ontrack build parameters in native pipeline syntax

**Comment by SansGuidon** [comment]
@dcoraboeuf started working on this, will create an issue and PR when happy with result locally ;)

**Comment by dcoraboeuf** [comment]
I'm looking forward to it :)
